image: ubuntu/latest
packages:
  - curl
  - unzip
sources:
  - https://git.sr.ht/~ruivieira/nim-template
tasks:
  - setup: |
      sudo apt-get update
      sudo apt-get install -y curl gcc xz-utils
      export CHOOSENIM_NO_ANALYTICS=1
      curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
      /home/build/.nimble/bin/choosenim stable
  - test: |
      export PATH=$HOME/.nimble/bin:$PATH
      cd nim-gitea
      nim --version
      nimble test
